### PR TITLE
added compc to build swc

### PR DESCRIPTION
**Pull request by lexoyo**
I have added compc to build swc, does it seem useful to you?

### CODE REVIEW

**Comment by lexoyo** [comment]
I also added something yo `install.js` so that mxmlc and compc are compatible with 64bit java

**Comment by lexoyo** [comment]
@JamesMGreene what do you think?

**Comment by noseglid** [comment]
You should fix the linting error Travis complains about: https://travis-ci.org/JamesMGreene/node-flex-sdk/builds/56972370

**Comment by lexoyo** [comment]
Ah ok :)
Done :shipit:

**Comment by JamesMGreene** [comment]
Sorry it took a little while to get around to this.

I won't accept the new "bin/compc" file as-is because I want it to be a Node.js script (basically a copy of the ["bin/mxmlc" file](https://github.com/JamesMGreene/node-flex-sdk/blob/master/bin/mxmlc), so please take a look at that one. Additionally, those files are not required to exist in order to use the tools, they are only convenience scripts that just wrap up the sinple underlying Node.js module.

I also don't believe that your changes to "install.js" are needed due to prior changes I've made in [prepublish.js#L175-212](https://github.com/JamesMGreene/node-flex-sdk/blob/master/prepublish.js#L175-212). Have you actually tried installing this module as a dependency to verify?

**Comment by JamesMGreene** [comment]
Closing this as the submitter did not update following my suggestions.

**Pull request closed without merging**
